---
deployment:
  tasks:
    - export DEPLOYPATH=/home/otodriveafrica/public_html/
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp contactscript.js $DEPLOYPATH
    - /bin/cp get-quote.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp maps.html $DEPLOYPATH
    - /bin/cp navbar.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp testimonial.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    
